hub:
   port: 4444
   environments:
       - name: "Firefox 3.6 on Mac OS X"
         browser: "*firefox /Applications/Firefox 3.6.app/Contents/MacOS/firefox-bin"
       - name: "Firefox 4.0 on Mac OS X"
         browser: "*firefox /Applications/Firefox 4.0.app/Contents/MacOS/firefox-bin"
       - name: "Firefox 3.6 on Windows 7"
         browser: "*firefox C:/Program Files/Mozilla Firefox 3.6/firefox.exe"
       - name: "Firefox 4.0 on Windows 7"
         browser: "*firefox C:/Program Files/Mozilla Firefox 4.0/firefox.exe"
       - name: "Internet Explorer 8 on Windows 7"
         browser: "*iexplore"
       - name: "Internet Explorer 9 on Windows 7"
         browser: "*iexplore"
